### ISSUE TITLE
"Failed to get/parse ioping output" after ioping update

### ISSUE THREAD

**Issue by catalinonem** [sensu-plugins/sensu-plugins-io-checks#10]
Hello guys,

I recently updated ioping package on my homeserver (CentOS Linux release 7.3.1611 ) and since Sensu plugin "metrics-ioping.rb" fails to get/parse ioping output. Can someone please help to investigate this issue?

Thank you for your support!

[root@vmm ~]# /usr/bin/sudo /etc/sensu/plugins/metrics-ioping.rb -n sda -d /dev/sda
Failed to get/parse ioping output

[root@vmm ~]#  grep ioping /var/log/yum.log
Jan 03 14:11:36 Updated: ioping-1.0-1.el7.x86_64

**Comment by catalinonem** [comment]
Hello,

Any news about this issue I am experiencing? 

Thank you in advance!

**Comment by Evesy** [comment]
@mattyjones @eheydrick 

Would it be possible to get a new gem cut which includes the changes from #9 ?

The EPEL repo now includes ioping 1.0 which is currently not supported due to the addition of nanosecond precision, which is breaking this plugin on certain installations

**Comment by majormoses** [comment]
Yes, I will take a look and cut a release.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-io-checks/versions/1.0.1

**Comment by majormoses** [comment]
@Evesy I am in the process of formally outlining when we should be releasing functional changes (does not include documentation, travis testing, rake tasks, etc). 

IMHO I believe that there is no good reason that functional changes should ever take more than 24 hours to release after acceptance. Assuming the changelog is properly groomed it takes less than 15 minutes to cut a release (much of it waiting on CI) if you are familiar with the process. Currently most of the active maintainers on plugins do not work for sensu and have full time jobs elsewhere otherwise I would push for always immediate releases. In most cases I try to run releases immediately after accepting changes if not I will usually do it that evening after work. Until this get's formalized if someone else has merged and not released within 24 hours please ping me and the maintainer that merged it so I can release and bring this up. 

@mbbroberg yet another case of why this needs to be formalized.
